# config file for transfer learning example on CIFAR100

training:
  batch_size: 63
  n_epochs: 15
  n_iters: 200001
  ngpu: 1
  snapshot_freq: 50
  algo: 'dsm'
  anneal_power: 2.0

data:
 dataset: "CIFAR100_transferBaseline"
 image_size: 32
 channels: 3
 logit_transform: false
 random_flip: true
 random_state: 0
 split_size: .33

model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ngf: 64
  final_layer: true
  feature_size: 200
  augment: false
  positive: false
  architecture: 'ConvMLP'

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false

n_labels: 85
